import { useMemo, useState } from 'react'
import type { ActivityData, ActivitySource, ActivityStatus } from '../models/activity'
import { StatePanel } from './StatePanel'
import './ActivityPage.css'
const sources: ActivitySource[] = ['Automations', 'Content', 'Jarvis', 'DocIQ', 'Tasks', 'Goals', 'Home', 'Health', 'Finances']
const statuses: ActivityStatus[] = ['success', 'attention', 'in-progress', 'info']
export function ActivityPage({ data }: { data: ActivityData }) {
  const [source, setSource] = useState<ActivitySource | 'all'>('all'); const [status, setStatus] = useState<ActivityStatus | 'all'>('all'); const [windowHours, setWindowHours] = useState(48)
  const [now] = useState(() => Date.now())
  const events = useMemo(() => data.events.filter(item => (source === 'all' || item.source === source) && (status === 'all' || item.status === status) && now - new Date(item.timestamp).getTime() <= windowHours * 3_600_000).sort((a, b) => b.timestamp.localeCompare(a.timestamp)), [data.events, source, status, windowHours, now])
  const time = (value: string) => new Intl.RelativeTimeFormat('en', { numeric: 'auto' }).format(-Math.max(1, Math.round((now - new Date(value).getTime()) / 3_600_000)), 'hour')
  return <div className="dashboard activity-page"><section className="activity-hero"><div><p className="eyebrow">Everything moving</p><h1>Activity</h1><p className="subtitle">One timeline for the work happening across LifeOS.</p></div><span>{events.length} recent events</span></section><section className="panel activity-panel"><div className="activity-filters"><label>Source<select value={source} onChange={event => setSource(event.target.value as typeof source)}><option value="all">All sources</option>{sources.map(item => <option key={item}>{item}</option>)}</select></label><label>Status<select value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></label><label>Time window<select value={windowHours} onChange={event => setWindowHours(Number(event.target.value))}><option value="24">Last 24 hours</option><option value="48">Last 48 hours</option><option value="168">Last 7 days</option></select></label></div><div className="timeline">{events.length ? events.map(item => <article key={item.id}><span className={`timeline-dot ${item.status}`} /><div><header><strong>{item.type}</strong><span>{item.source}</span></header><p>{item.description}</p><footer><time dateTime={item.timestamp}>{time(item.timestamp)}</time>{item.route && <a href={`#/${item.route}`}>Open workspace →</a>}</footer></div></article>) : <StatePanel kind="empty" title="No activity in this view" description="Try a wider time window or different filters." />}</div></section></div>
}
