import { useMemo, useState } from 'react'
import type { ActivityData, ActivitySource, ActivityStatus } from '../models/activity'
import { StatePanel } from './StatePanel'
import './ActivityPage.css'
import './ActivityPersistent.css'
const statuses: ActivityStatus[] = ['success', 'attention', 'in-progress', 'info']
export function ActivityPage({ data }: { data: ActivityData }) {
  const [source, setSource] = useState<ActivitySource | 'all'>('all'); const [status, setStatus] = useState<ActivityStatus | 'all'>('all'); const [windowHours, setWindowHours] = useState(48); const [limit, setLimit] = useState(20); const [now] = useState(() => Date.now())
  const sources = [...new Set(data.events.map(item => item.source))]
  const events = useMemo(() => data.events.filter(item => (source === 'all' || item.source === source) && (status === 'all' || item.status === status) && now - new Date(item.timestamp).getTime() <= windowHours * 3_600_000).sort((a, b) => b.timestamp.localeCompare(a.timestamp)), [data.events, source, status, windowHours, now])
  const time = (value: string) => new Intl.RelativeTimeFormat('en', { numeric: 'auto' }).format(-Math.max(1, Math.round((now - new Date(value).getTime()) / 3_600_000)), 'hour')
  return <div className="dashboard activity-page"><section className="activity-hero"><div><p className="eyebrow">Everything moving</p><h1>Activity</h1><p className="subtitle">One durable timeline for work across LifeOS.</p></div><span>{events.length} recent events</span></section><section className="panel activity-panel"><div className="activity-filters"><label>Source<select value={source} onChange={event => { setSource(event.target.value as typeof source); setLimit(20) }}><option value="all">All sources</option>{sources.map(item => <option key={item}>{item}</option>)}</select></label><label>Status<select value={status} onChange={event => { setStatus(event.target.value as typeof status); setLimit(20) }}><option value="all">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></label><label>Time window<select value={windowHours} onChange={event => { setWindowHours(Number(event.target.value)); setLimit(20) }}><option value="24">Last 24 hours</option><option value="48">Last 48 hours</option><option value="168">Last 7 days</option></select></label></div><div className="timeline">{events.length ? events.slice(0,limit).map(item => <article key={item.id}><span className={`timeline-dot ${item.status}`} /><div><header><strong>{item.type}</strong><span>{item.source}</span></header><p>{item.description}</p><footer><time dateTime={item.timestamp}>{time(item.timestamp)}</time>{(item.correlationId || item.runId) && <small>{item.runId ?? item.correlationId}</small>}{item.route && <a href={`#/${item.route}`}>Open workspace →</a>}</footer></div></article>) : <StatePanel kind="empty" title="No activity in this view" description="Try a wider time window or different filters." />}</div>{events.length > limit && <button className="activity-load" onClick={() => setLimit(current => current + 20)}>Load more events</button>}</section></div>
}
