import { useState } from 'react'
import type { AgentControlAction, AgentTask } from '../models/agentControl'
import type { AgentControlService } from '../services/AgentControlService'
import { ErrorState } from './PageState'
import './AgentControlPage.css'

export function AgentControlPage({ service }: { service: AgentControlService }) {
  const [data, setData] = useState(() => service.getStatus()); const [pending, setPending] = useState<{ action: AgentControlAction; task: AgentTask } | null>(null); const [message, setMessage] = useState('')
  const run = (action: AgentControlAction, task: AgentTask) => { const result = service.control({ action, taskId: task.id, idempotencyKey: `${task.id}:${action}:${task.updatedAt}` }); setMessage(result.message); setData(service.getStatus()); setPending(null) }
  const request = (action: AgentControlAction, task: AgentTask) => action === 'stop' || action === 'retry' ? setPending({ action, task }) : run(action, task)
  if (data.connection === 'unavailable') return <div className="agent-page"><ErrorState title="Agent provider unavailable" description={data.message ?? 'Monitoring data cannot be loaded right now.'} /></div>
  const grouped = (state: AgentTask['state']) => data.tasks.filter(task => task.state === state)
  return <div className="agent-page"><section className="agent-hero"><div><p className="eyebrow">Agent operations</p><h1>Control Center</h1><p className="subtitle">Monitor freely. Control deliberately.</p></div><span className={`agent-provider ${data.agentStatus}`}>{data.provider} · {data.agentStatus}</span></section>{message && <p className="agent-message" role="status">{message}</p>}<section className="agent-overview"><div><strong>{grouped('current').length}</strong><span>Running</span></div><div><strong>{grouped('queued').length}</strong><span>Queued</span></div><div><strong>{grouped('completed').length}</strong><span>Completed</span></div><div><strong>{grouped('failed').length}</strong><span>Failures</span></div></section><div className="agent-grid">{data.tasks.map(task => <article className={`agent-task ${task.state}`} key={task.id}><header><span>{task.state}</span><time>{new Intl.DateTimeFormat(undefined,{timeStyle:'short'}).format(new Date(task.updatedAt))}</time></header><h2>{task.title}</h2><p>{task.detail}</p>{task.error && <p className="agent-error">{task.error}</p>}<footer>{task.state === 'queued' && <button onClick={() => request('start',task)}>Start</button>}{task.state === 'current' && <button onClick={() => request('stop',task)}>Stop</button>}{task.state === 'paused' && <button onClick={() => request('resume',task)}>Resume</button>}{task.state === 'failed' && <button onClick={() => request('retry',task)}>Retry</button>}</footer></article>)}</div>{pending && <div className="agent-dialog-backdrop"><section className="agent-dialog" role="alertdialog" aria-modal="true" aria-labelledby="agent-confirm-title"><p className="eyebrow">Confirmation required</p><h2 id="agent-confirm-title">{pending.action === 'stop' ? 'Stop current work?' : 'Retry failed task?'}</h2><p>{pending.task.title}</p><div><button className="text-button" onClick={() => setPending(null)}>Cancel</button><button className="primary-button" onClick={() => run(pending.action,pending.task)}>Confirm {pending.action}</button></div></section></div>}</div>
}
