import { useState } from 'react'
import type { AssistantMessage } from '../models/assistant'
import type { AssistantService } from '../services/AssistantService'
import './AssistantPage.css'

const suggestions = ['What should I work on today?','What failed overnight?','How is Jarvis performing?','Generate today’s content']
export function AssistantPage({ service }: { service: AssistantService }) {
  const [messages, setMessages] = useState<AssistantMessage[]>([{ id: 'welcome', role: 'assistant', text: 'Ask about your LifeOS context or request an approved action.' }]); const [input, setInput] = useState(''); const [pending, setPending] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (text: string, approved = false) => { if (!text.trim()) return; setBusy(true); if (!approved) setMessages(current => [...current, { id: `user-${Date.now()}`, role: 'user', text }]); const result = await service.ask(text, approved); setMessages(current => [...current, { id: `assistant-${Date.now()}`, role: 'assistant', text: result.text, tool: result.tool, state: result.kind }]); setPending(result.kind === 'approval-required' ? text : ''); setInput(''); setBusy(false) }
  return <div className="assistant-page"><section className="assistant-hero"><div><p className="eyebrow">LifeOS intelligence</p><h1>AI Assistant</h1><p className="subtitle">Answers grounded in your services, actions governed by approval.</p></div><span>Typed tools · approval aware</span></section><section className="panel assistant-panel"><div className="assistant-thread" aria-live="polite">{messages.map(message => <article className={`assistant-message ${message.role} ${message.state ?? ''}`} key={message.id}><span>{message.role === 'assistant' ? 'LifeOS' : 'You'}</span><p>{message.text}</p>{message.tool && <small>Tool · {message.tool}</small>}</article>)}</div>{pending && <div className="assistant-approval" role="alert"><strong>Approval required</strong><p>This action can write through an external provider.</p><button className="text-button" onClick={() => setPending('')}>Cancel</button><button className="primary-button" onClick={() => void submit(pending,true)}>Approve action</button></div>}<div className="assistant-suggestions">{suggestions.map(item => <button onClick={() => void submit(item)} disabled={busy} key={item}>{item}</button>)}</div><form onSubmit={event => { event.preventDefault(); void submit(input) }}><label htmlFor="assistant-input">Message LifeOS</label><input id="assistant-input" value={input} onChange={event => setInput(event.target.value)} placeholder="What needs my attention?" /><button className="primary-button" disabled={busy || !input.trim()}>Send</button></form></section></div>
}
