import type { Automation, AutomationStatus } from '../models/automation'
import type { DashboardIcon } from '../models/dashboard'
import { StatePanel } from './StatePanel'

const statusLabels: Record<AutomationStatus, string> = { active: 'Active', scheduled: 'Scheduled', completed: 'Completed', failed: 'Failed', blocked: 'Blocked' }
interface IconProps { name: DashboardIcon; size?: number }
type PageState = 'ready' | 'loading' | 'error'
interface AutomationsPageProps { data: Record<AutomationStatus, Automation[]>; icon: (props: IconProps) => React.ReactNode; state?: PageState }
function AutomationCard({ automation, icon: Icon }: { automation: Automation; icon: AutomationsPageProps['icon'] }) { return <article className="automation-card"><div className={`automation-icon ${automation.tone}`}><Icon name={automation.icon} /></div><div className="automation-card-copy"><div className="automation-title-row"><h3>{automation.name}</h3><span className={`status-badge ${automation.status}`}>{statusLabels[automation.status]}</span></div><p>{automation.description}</p><div className="automation-meta"><span><Icon name="clock" size={13} />Last run: {automation.lastRun}</span>{automation.nextRun && <span><Icon name="clock" size={13} />Next: {automation.nextRun}</span>}</div></div><button className="card-menu" aria-label={`More options for ${automation.name}`}><Icon name="more" size={18} /></button></article> }
function AutomationRow({ automation, icon: Icon }: { automation: Automation; icon: AutomationsPageProps['icon'] }) { return <article className="automation-row"><div className={`small-icon ${automation.tone}`}><Icon name={automation.icon} size={17} /></div><div className="automation-row-copy"><h3>{automation.name}</h3><p>{automation.description}</p></div><span className={`status-badge ${automation.status}`}>{statusLabels[automation.status]}</span><div className="row-meta"><span><Icon name="clock" size={13} />{automation.lastRun}</span><span>{automation.issue ?? automation.runs ?? automation.schedule}</span></div><button className="card-menu" aria-label={`More options for ${automation.name}`}><Icon name="more" size={18} /></button></article> }
function AutomationSection({ title, eyebrow, items, icon: Icon, cardView = false }: { title: string; eyebrow: string; items: Automation[]; icon: AutomationsPageProps['icon']; cardView?: boolean }) { return <section className="automation-section"><div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}<span>{items.length}</span></h2></div>{items.length > 0 && <button className="text-button">View all <Icon name="arrow" size={16} /></button>}</div>{items.length === 0 ? <StatePanel kind="empty" title={`No ${title.toLowerCase()} yet`} description="New automation activity will appear here." /> : <div className={cardView ? 'automation-card-grid' : 'automation-rows'}>{items.map(item => cardView ? <AutomationCard automation={item} icon={Icon} key={item.id} /> : <AutomationRow automation={item} icon={Icon} key={item.id} />)}</div>}</section> }
export function AutomationsPage({ data, icon: Icon, state = 'ready' }: AutomationsPageProps) {
  const title = <section className="automations-hero"><div><p className="eyebrow">Workflow control</p><h1>Automations</h1><p className="subtitle">Keep your personal systems moving with calm, visible control.</p></div>{state === 'ready' && <button className="primary-button">Create automation <Icon name="bolt" size={17} /></button>}</section>
  if (state === 'loading') return <div className="dashboard automations-page">{title}<section className="automation-section"><StatePanel kind="loading" title="Loading automations" description="Gathering the latest workflow activity." /></section></div>
  if (state === 'error') return <div className="dashboard automations-page">{title}<section className="automation-section"><StatePanel kind="error" title="Unable to load automations" description="Try again when your workspace connection is available." /></section></div>
  return <div className="dashboard automations-page">{title}<section className="automation-overview"><div><strong>{data.active.length}</strong><span>Active systems</span></div><div><strong>{data.scheduled.length}</strong><span>Upcoming runs</span></div><div><strong>{data.failed.length + data.blocked.length}</strong><span>Need attention</span></div></section><AutomationSection title="Active automations" eyebrow="Running now" items={data.active} icon={Icon} cardView /><div className="automation-lower-grid"><AutomationSection title="Scheduled" eyebrow="Up next" items={data.scheduled} icon={Icon} /><AutomationSection title="Recently completed" eyebrow="Run history" items={data.completed} icon={Icon} /></div><div className="automation-lower-grid attention-grid"><AutomationSection title="Failed" eyebrow="Needs review" items={data.failed} icon={Icon} /><AutomationSection title="Blocked" eyebrow="Waiting on input" items={data.blocked} icon={Icon} /></div></div>
}
