import { useMemo, useState } from 'react'
import type { AutomationRun, AutomationRunStatus } from '../models/automation'
import { EmptyState } from './PageState'
import './AutomationHistoryPage.css'

const statuses: AutomationRunStatus[] = ['completed','failed','canceled','retried']
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const initialRun = () => new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('run')

export function AutomationHistoryPage({ runs }: { runs: AutomationRun[] }) {
  const [automation, setAutomation] = useState('all'); const [status, setStatus] = useState<AutomationRunStatus | 'all'>('all'); const [date, setDate] = useState('all'); const [selectedId, setSelectedId] = useState<string | null>(initialRun); const [now] = useState(() => Date.now())
  const filtered = useMemo(() => runs.filter(run => (automation === 'all' || run.automationId === automation) && (status === 'all' || run.status === status) && (date === 'all' || now - Date.parse(run.startedAt) <= Number(date) * 86_400_000)), [runs, automation, status, date, now])
  const selected = runs.find(run => run.id === selectedId)
  const automations = [...new Map(runs.map(run => [run.automationId, run.automationName])).entries()]
  return <div className="history-page"><section className="history-hero"><div><p className="eyebrow">Observable automation</p><h1>Execution history</h1><p className="subtitle">Inspect every run, retry, failure, cancellation, and event trigger.</p></div><a className="primary-button" href="#/automations">Automations</a></section><section className="panel history-panel"><div className="history-filters"><label>Automation<select value={automation} onChange={event => setAutomation(event.target.value)}><option value="all">All automations</option>{automations.map(([id,name]) => <option value={id} key={id}>{name}</option>)}</select></label><label>Status<select value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></label><label>Date<select value={date} onChange={event => setDate(event.target.value)}><option value="all">All time</option><option value="1">Last 24 hours</option><option value="7">Last 7 days</option></select></label></div>{filtered.length ? <div className="history-table" role="list">{filtered.map(run => <button className={run.id === selectedId ? 'selected' : ''} onClick={() => setSelectedId(run.id)} key={run.id} role="listitem"><span className={`history-status ${run.status}`}>{run.status}</span><span><strong>{run.automationName}</strong><small>{run.trigger} · {formatDate(run.startedAt)}</small></span><span>{Math.round(run.durationMs / 1000)}s</span><span>{run.retryCount} retries</span></button>)}</div> : <EmptyState title="No matching runs" description="Try changing the automation, status, or date filters." />}</section>{selected && <section className="panel run-detail"><div className="panel-heading"><div><p className="eyebrow">Run {selected.id}</p><h2>{selected.automationName}</h2></div><button className="text-button" onClick={() => setSelectedId(null)}>Close</button></div><dl><div><dt>Started</dt><dd>{formatDate(selected.startedAt)}</dd></div><div><dt>Ended</dt><dd>{formatDate(selected.endedAt)}</dd></div><div><dt>Trigger</dt><dd>{selected.trigger}</dd></div>{selected.triggerSource && <div><dt>Trigger source</dt><dd>{selected.triggerSource}</dd></div>}{selected.correlationId && <div><dt>Correlation</dt><dd>{selected.correlationId}</dd></div>}<div><dt>Retries</dt><dd>{selected.retryCount}</dd></div></dl><h3>Output</h3><p>{selected.outputSummary}</p>{selected.errorDetails && <><h3>Failure details</h3><pre>{selected.errorDetails}</pre></>}<footer>{selected.relatedLinks.map(link => <a href={link.href} key={link.href}>{link.label} →</a>)}</footer></section>}</div>
}
