import { useEffect, useMemo, useRef, useState } from 'react'
import type { SearchService } from '../services/SearchService'
import type { CommandRegistry } from '../services/CommandRegistry'
import type { LifeOSCommand } from '../models/command'
import './CommandPalette.css'

export function CommandPalette({ registry, searchService }: { registry: CommandRegistry; searchService: SearchService }) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [active, setActive] = useState(0)
  const [message, setMessage] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)
  const dialogRef = useRef<HTMLElement>(null)
  const close = () => { setOpen(false); setQuery(''); setActive(0); setMessage('') }
  const go = (route: string, action?: string) => { window.history.pushState(null, '', `#/${route}${action ? `?action=${action}` : ''}`); window.dispatchEvent(new HashChangeEvent('hashchange')); close() }
  const commands = useMemo(() => registry.list(), [registry])
  const run = (command: LifeOSCommand) => { if (!command.enabled) { setMessage(command.unavailableReason ?? 'This action is unavailable.'); return } if (command.requiresApproval && !window.confirm(`Run “${command.label}”?`)) return; go(command.target.route, command.target.action) }
  const filtered = useMemo(() => { const words = query.toLowerCase().split(/\s+/).filter(Boolean); return commands.filter(command => words.every(word => `${command.label} ${command.category} ${command.keywords.join(' ')}`.toLowerCase().includes(word))) }, [commands, query])
  const searchGroups = useMemo(() => searchService.search(query), [query, searchService])
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(value => !value) } else if (event.key === 'Escape') close() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  useEffect(() => { if (open) requestAnimationFrame(() => inputRef.current?.focus()) }, [open])
  return <><button className="search command-trigger" onClick={() => setOpen(true)} aria-haspopup="dialog" aria-expanded={open}><span aria-hidden="true">⌕</span><span>Search or run a command</span><kbd>⌘ K</kbd></button>{open && <div className="command-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) close() }}><section ref={dialogRef} className="command-dialog" role="dialog" aria-modal="true" aria-label="Command palette" onKeyDown={event => { if (event.key !== 'Tab') return; const focusable = [...(dialogRef.current?.querySelectorAll<HTMLElement>('button,input,[href],[tabindex]:not([tabindex="-1"])') ?? [])]; if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }}><div className="command-input"><span aria-hidden="true">⌕</span><input ref={inputRef} value={query} onChange={event => { setQuery(event.target.value); setActive(0); setMessage('') }} onKeyDown={event => { if (event.key === 'ArrowDown') { event.preventDefault(); setActive(value => Math.min(value + 1, filtered.length - 1)) } if (event.key === 'ArrowUp') { event.preventDefault(); setActive(value => Math.max(value - 1, 0)) } if (event.key === 'Enter' && filtered[active]) { event.preventDefault(); run(filtered[active]) } }} placeholder="Search workspaces and data…" aria-label="Search commands and workspace data" aria-controls="command-results" aria-activedescendant={filtered[active] ? `command-${filtered[active].id}` : undefined} /><kbd>Esc</kbd></div>{message && <p className="command-message" role="status">{message}</p>}<div className="command-results" id="command-results" role="listbox" aria-label="Command results">{filtered.length > 0 && <p className="command-group-label">Commands</p>}{filtered.map((command, index) => <button id={`command-${command.id}`} key={command.id} className={`${index === active ? 'active' : ''} ${command.enabled ? '' : 'disabled'}`} role="option" aria-selected={index === active} aria-disabled={!command.enabled} onMouseEnter={() => setActive(index)} onClick={() => run(command)}><span>{command.label}</span><small>{command.enabled ? command.category : command.unavailableReason}</small></button>)}{searchGroups.map(group => <section className="search-group" aria-label={`${group.source} search results`} key={group.source}><p className="command-group-label">{group.source}</p>{group.results.map(item => <button key={`${item.source}-${item.id}`} onClick={() => go(item.route)}><span><strong>{item.title}</strong><small>{item.description}</small></span><small>Open</small></button>)}</section>)}{!filtered.length && !searchGroups.length && <p role="status">No matching results</p>}</div></section></div>}</>
}
