import type { DocIQData, RiskSeverity } from '../models/dociq'

interface DocIQPageProps { data: DocIQData; icon: (name: 'files' | 'scan' | 'check' | 'alert' | 'review' | 'folder' | 'upload' | 'arrow' | 'more') => React.ReactNode }
const severityClass: Record<RiskSeverity, string> = { High: 'risk-high', Medium: 'risk-medium', Low: 'risk-low' }

export function DocIQPage({ data, icon }: DocIQPageProps) {
  return <div className="dashboard dociq-page">
    <section className="dociq-welcome"><div><p className="eyebrow">Document intelligence</p><h1>DocIQ</h1><p className="subtitle">Turn every document into a clear next step.</p></div><div className="dociq-header-actions"><span className="freshness"><span className="status-dot" />{data.updatedLabel}</span><a className="primary-button" href={data.actions.find(action => action.icon === 'upload')?.href ?? '#/dociq'} target={data.actions.find(action => action.icon === 'upload')?.href ? '_blank' : undefined} rel="noreferrer">Upload documents {icon('upload')}</a></div></section>
    <section className="dociq-metrics">{data.metrics.map(metric => <article className="dociq-metric" key={metric.label}><div className={`card-icon ${metric.tone}`}>{icon(metric.icon)}</div><p>{metric.label}</p><strong>{metric.value}</strong><span>{metric.detail}</span></article>)}</section>
    <div className="dociq-content-grid"><section className="panel analyses-panel"><div className="panel-heading"><div><p className="eyebrow">Document activity</p><h2>Recent analyses</h2></div><a className="text-button" href={data.actions.find(action => action.icon === 'review')?.href ?? '#/dociq'} target={data.actions.find(action => action.icon === 'review')?.href ? '_blank' : undefined} rel="noreferrer">View all {icon('arrow')}</a></div><div className="analysis-table"><div className="analysis-table-head"><span>Document</span><span>Status</span><span>Confidence</span></div>{data.recentAnalyses.map(item => <article className="analysis-row" key={item.name}><div className="document-name"><div className="document-icon">{icon('files')}</div><div><h3>{item.name}</h3><p>{item.type} · {item.updatedAt}</p></div></div><span className={`document-state ${item.state.toLowerCase().replace(' ', '-')}`}>{item.state}</span><strong>{item.score}</strong></article>)}</div></section><section className="panel risks-panel"><div className="panel-heading"><div><p className="eyebrow">Needs attention</p><h2>Flagged risks</h2></div><span>{data.risks.length}</span></div><div className="risk-list">{data.risks.map(risk => <article className="risk-item" key={risk.title}><span className={`risk-severity ${severityClass[risk.severity]}`}>{risk.severity}</span><div><h3>{risk.title}</h3><p>{risk.document}</p><small>{risk.detail}</small></div><button className="icon-button" aria-label={`More options for ${risk.title}`}>{icon('more')}</button></article>)}</div></section></div>
    <div className="dociq-lower-grid"><section className="panel actions-panel"><div className="panel-heading"><div><p className="eyebrow">Guided workflow</p><h2>Recommended actions</h2></div></div><div className="action-list">{data.actions.map(action => <article className="dociq-action" key={action.title}><div className="small-icon blue">{icon(action.icon)}</div><div><h3>{action.title}</h3><p>{action.detail}</p></div>{action.href ? <a className="text-button" href={action.href} target="_blank" rel="noreferrer">{action.action} {icon('arrow')}</a> : <button className="text-button">{action.action} {icon('arrow')}</button>}</article>)}</div></section><section className="panel system-panel"><div className="panel-heading"><div><p className="eyebrow">Platform health</p><h2>System status</h2></div></div><div className="system-list">{data.systemStatus.map(system => <article key={system.name}><div><h3>{system.name}</h3><p>{system.detail}</p></div><span className={system.status === 'Operational' ? 'system-ok' : 'system-monitoring'}>{system.status}</span></article>)}</div></section></div>
  </div>
}
