import { useState } from 'react'
import type { GitHubProjectData, GitHubProjectItem } from '../models/githubProject'
import { ErrorState, LoadingState } from './PageState'
import './GitHubProjectPage.css'

function ItemList({ title, items }: { title: string; items: GitHubProjectItem[] }) { return <section className="panel github-section"><div className="panel-heading"><div><p className="eyebrow">{items.length} items</p><h2>{title}</h2></div></div>{items.map(item => <a href={item.url} target="_blank" rel="noreferrer" key={item.id}><span className={`github-state ${item.state}`}>{item.state}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><span>↗</span></a>)}</section> }
export function GitHubProjectPage({ data }: { data: GitHubProjectData }) {
  const [selected, setSelected] = useState(data.repositories[0]?.fullName ?? ''); const repository = data.repositories.find(item => item.fullName === selected)
  if (data.connection === 'loading') return <div className="github-page"><LoadingState title="Loading GitHub projects" description="Reading repository delivery signals." /></div>
  if (data.connection === 'unauthorized' || data.connection === 'disconnected') return <div className="github-page"><ErrorState title={data.connection === 'unauthorized' ? 'GitHub authorization required' : 'GitHub disconnected'} description={data.message ?? 'Connect a GitHub provider to view project health.'} /></div>
  return <div className="github-page"><section className="github-hero"><div><p className="eyebrow">Software delivery</p><h1>GitHub Projects</h1><p className="subtitle">Issues, changes, checks, and agent work in one operational view.</p></div><select aria-label="Select repository" value={selected} onChange={event => setSelected(event.target.value)}>{data.repositories.map(item => <option key={item.fullName}>{item.fullName}</option>)}</select></section>{data.connection === 'stale' && <p className="github-warning" role="status">This snapshot may be stale. Links still open the source on GitHub.</p>}{repository && <><section className="github-repo-bar"><a href={repository.url} target="_blank" rel="noreferrer">{repository.fullName} ↗</a><span>Default branch · {repository.defaultBranch}</span><span>Updated {data.fetchedAt && new Intl.DateTimeFormat(undefined, { timeStyle: 'short' }).format(new Date(data.fetchedAt))}</span></section><div className="github-grid"><ItemList title="Open issues" items={repository.issues} /><ItemList title="Pull requests" items={repository.pullRequests} /><ItemList title="CI & checks" items={repository.checks} /><ItemList title="Recent commits" items={repository.commits} /><ItemList title="Agent activity" items={repository.agentActivity} /></div></>}</div>
}
