import { useState } from 'react'
import type { GoalData, GoalKpi, KpiData, KpiFrequency } from '../models/goal'
import { kpiProgress, kpiTrend, MockKpiService } from '../services/KpiService'
import { storageKeys } from '../storage/storageKeys'
import { usePersistentState } from '../storage/usePersistentState'
import './KpisPage.css'
const frequencies:KpiFrequency[]=['daily','weekly','monthly','quarterly']
const defaultData = new MockKpiService().getKpiData()
export function KpisPage({data=defaultData,goals}:{data?:KpiData;goals:GoalData}){
 const[kpis,setKpis]=usePersistentState(storageKeys.kpis,data.kpis);const[editing,setEditing]=useState<GoalKpi|null>(null)
 const create=()=>setEditing({id:`kpi-${Date.now()}`,name:'New KPI',area:'Business',target:100,current:0,unit:'units',frequency:'monthly',status:'on-track',history:[]})
 const save=()=>{if(!editing)return;setKpis(current=>current.some(item=>item.id===editing.id)?current.map(item=>item.id===editing.id?editing:item):[...current,editing]);setEditing(null)}
 return <div className="kpi-page"><section className="kpi-hero"><div><p className="eyebrow">Goals & measurement</p><h1>KPIs</h1><p className="subtitle">Turn long-range outcomes into visible, measurable momentum.</p></div><button className="primary-button" onClick={create}>Create KPI</button></section>{editing&&<section className="panel kpi-editor"><div className="panel-heading"><h2>Edit KPI</h2><button className="text-button" onClick={()=>setEditing(null)}>Cancel</button></div><div><label>Name<input value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})}/></label><label>Current<input type="number" value={editing.current} onChange={event=>setEditing({...editing,current:Number(event.target.value)})}/></label><label>Target<input type="number" value={editing.target} onChange={event=>setEditing({...editing,target:Number(event.target.value)})}/></label><label>Unit<input value={editing.unit} onChange={event=>setEditing({...editing,unit:event.target.value})}/></label><label>Frequency<select value={editing.frequency} onChange={event=>setEditing({...editing,frequency:event.target.value as KpiFrequency})}>{frequencies.map(item=><option key={item}>{item}</option>)}</select></label><label>Linked goal<select value={editing.goalId??''} onChange={event=>setEditing({...editing,goalId:event.target.value||undefined})}><option value="">No linked goal</option>{goals.goals.map(goal=><option value={goal.id} key={goal.id}>{goal.title}</option>)}</select></label><button className="primary-button" onClick={save}>Save KPI</button></div></section>}<section className="kpi-grid">{kpis.filter(kpi=>kpi.status!=='archived').map(kpi=>{const progress=kpiProgress(kpi),trend=kpiTrend(kpi);return <article className="kpi-card" key={kpi.id}><header><span>{kpi.area} · {kpi.frequency}</span><strong className={kpi.status}>{kpi.status}</strong></header><h2>{kpi.name}</h2><div className="kpi-value"><strong>{kpi.current.toLocaleString()} {kpi.unit}</strong><span>of {kpi.target.toLocaleString()}</span></div><div className="kpi-track" aria-label={`${progress}% of target`}><span style={{width:`${progress}%`}}/></div><div className="kpi-meta"><span>{progress}% complete</span><span>{trend>=0?'↑':'↓'} {Math.abs(trend)}%</span></div><div className="kpi-history" aria-label="Historical snapshots">{kpi.history.map(snapshot=><div key={snapshot.at}><time>{snapshot.at.slice(0,7)}</time><span>{snapshot.value.toLocaleString()}</span></div>)}</div><footer><button onClick={()=>setEditing(kpi)}>Edit</button><button onClick={()=>setKpis(current=>current.map(item=>item.id===kpi.id?{...item,status:'archived'}:item))}>Archive</button></footer></article>})}</section></div>
}
