import { useMemo, useState } from 'react'
import type { ProjectData, ProjectDomain, ProjectStatus } from '../models/project'
import { usePersistentState } from '../storage/usePersistentState'
import './WorkspaceCollection.css'
export function ProjectsPage({ data }: { data: ProjectData }) {
  const [projects, setProjects] = usePersistentState('projects', data.projects); const [status, setStatus] = useState<ProjectStatus | 'all'>('all'); const [domain, setDomain] = useState<ProjectDomain | 'all'>('all'); const [selected, setSelected] = useState(projects[0]?.id)
  const shown = useMemo(() => projects.filter(project => (status === 'all' || project.status === status) && (domain === 'all' || project.domain === domain)), [projects, status, domain]); const detail = projects.find(project => project.id === selected)
  const toggle = (projectId: string, milestoneId: string) => setProjects(current => current.map(project => project.id !== projectId ? project : { ...project, milestones: project.milestones.map(item => item.id === milestoneId ? { ...item, completed: !item.completed } : item), progress: Math.round(project.milestones.map(item => item.id === milestoneId ? { ...item, completed: !item.completed } : item).filter(item => item.completed).length / project.milestones.length * 100) }))
  return <div className="dashboard"><section className="workspace-hero"><div><p className="eyebrow">Outcomes in motion</p><h1>Projects</h1><p className="subtitle">Milestones, linked work, and progress in one place.</p></div><div className="workspace-controls"><select aria-label="Project status" value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option><option>active</option><option>planning</option><option>paused</option><option>completed</option></select><select aria-label="Project domain" value={domain} onChange={event => setDomain(event.target.value as typeof domain)}><option value="all">All domains</option>{[...new Set(projects.map(item => item.domain))].map(item => <option key={item}>{item}</option>)}</select></div></section><section className="workspace-grid">{shown.map(project => <article className={`workspace-card ${selected === project.id ? 'selected' : ''}`} key={project.id}><header><span className="workspace-pill">{project.domain}</span><small>{project.status}</small></header><h2>{project.title}</h2><p>{project.description}</p><div className="workspace-progress"><span style={{ width: `${project.progress}%` }} /></div><footer><span>{project.progress}% · {project.linkedTaskIds.length} linked tasks</span><button onClick={() => setSelected(project.id)}>View details</button></footer></article>)}</section>{detail && <section className="panel workspace-detail"><p className="eyebrow">Project detail</p><h2>{detail.title}</h2><div className="workspace-list">{detail.milestones.map(item => <button className={item.completed ? 'done' : ''} onClick={() => toggle(detail.id, item.id)} key={item.id}><span>{item.completed ? '✓' : '○'} {item.title}</span><small>{item.completed ? 'Complete' : 'Pending'}</small></button>)}</div></section>}</div>
}
