import { useState } from 'react'
import type { AutomationSchedule, ScheduleData } from '../models/automation'
import { calculateNextRun } from '../services/ScheduleService'
import { storageKeys } from '../storage/storageKeys'
import { usePersistentState } from '../storage/usePersistentState'
import { EmptyState } from './PageState'
import './SchedulesPage.css'

const cadenceLabel = (schedule: AutomationSchedule) => schedule.cadence.type === 'daily' ? `Daily at ${schedule.cadence.time}` : schedule.cadence.type === 'weekly' ? `Weekly · day ${schedule.cadence.weekday} at ${schedule.cadence.time}` : `Every ${schedule.cadence.intervalDays} days at ${schedule.cadence.time}`
const formatRun = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Never'

export function SchedulesPage({ data }: { data: ScheduleData }) {
  const [schedules, setSchedules] = usePersistentState(storageKeys.schedules, data.schedules)
  const [editing, setEditing] = useState<AutomationSchedule | null>(null)
  const startNew = () => { const cadence = { type: 'daily' as const, time: '07:00' }; setEditing({ id: `schedule-${Date.now()}`, automationId: 'custom-automation', name: 'New schedule', enabled: true, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', cadence, nextRun: calculateNextRun(cadence, Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', new Date()), executionState: 'idle' }) }
  const save = () => { if (!editing) return; const nextRun = calculateNextRun(editing.cadence, editing.timezone, new Date()); setSchedules(current => current.some(item => item.id === editing.id) ? current.map(item => item.id === editing.id ? { ...editing, nextRun } : item) : [...current, { ...editing, nextRun }]); setEditing(null) }
  const updateCadence = (type: 'daily' | 'weekly' | 'custom') => setEditing(current => current ? { ...current, cadence: type === 'daily' ? { type, time: '07:00' } : type === 'weekly' ? { type, weekday: 1, time: '07:00' } : { type, intervalDays: 2, time: '07:00', anchorDate: new Date().toISOString().slice(0, 10) } } : current)
  const updateWeekday = (weekday: number) => setEditing(current => current?.cadence.type === 'weekly' ? { ...current, cadence: { ...current.cadence, weekday } } : current)
  const updateInterval = (intervalDays: number) => setEditing(current => current?.cadence.type === 'custom' ? { ...current, cadence: { ...current.cadence, intervalDays } } : current)
  return <div className="schedules-page">
    <section className="schedules-hero"><div><p className="eyebrow">Automation backbone</p><h1>Schedules</h1><p className="subtitle">Recurring jobs with visible timing and execution state.</p></div><button className="primary-button" onClick={startNew}>Create schedule</button></section>
    {editing && <section className="panel schedule-editor" aria-label="Schedule editor"><div className="panel-heading"><div><p className="eyebrow">Configuration</p><h2>{schedules.some(item => item.id === editing.id) ? 'Edit schedule' : 'New schedule'}</h2></div><button className="text-button" onClick={() => setEditing(null)}>Cancel</button></div><div className="schedule-form"><label>Name<input value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><label>Cadence<select value={editing.cadence.type} onChange={event => updateCadence(event.target.value as 'daily' | 'weekly' | 'custom')}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="custom">Custom interval</option></select></label><label>Time<input type="time" value={editing.cadence.time} onChange={event => setEditing({ ...editing, cadence: { ...editing.cadence, time: event.target.value } })} /></label><label>Timezone<select value={editing.timezone} onChange={event => setEditing({ ...editing, timezone: event.target.value })}><option value="UTC">UTC</option><option value="America/New_York">Eastern Time</option><option value="America/Chicago">Central Time</option><option value="America/Denver">Mountain Time</option><option value="America/Los_Angeles">Pacific Time</option><option value="Europe/London">London</option></select></label>{editing.cadence.type === 'weekly' && <label>Weekday<select value={editing.cadence.weekday} onChange={event => updateWeekday(Number(event.target.value))}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day, index) => <option value={index} key={day}>{day}</option>)}</select></label>}{editing.cadence.type === 'custom' && <label>Interval days<input type="number" min="1" value={editing.cadence.intervalDays} onChange={event => updateInterval(Math.max(1, Number(event.target.value)))} /></label>}<button className="primary-button" onClick={save} disabled={!editing.name.trim()}>Save schedule</button></div></section>}
    {schedules.length ? <section className="schedule-grid" aria-label="Automation schedules">{schedules.map(schedule => <article className={`schedule-card ${schedule.enabled ? '' : 'disabled'}`} key={schedule.id}><header><span className={`schedule-state ${schedule.executionState}`}>{schedule.executionState}</span><label className="schedule-toggle"><input type="checkbox" checked={schedule.enabled} onChange={event => setSchedules(current => current.map(item => item.id === schedule.id ? { ...item, enabled: event.target.checked } : item))} />{schedule.enabled ? 'Enabled' : 'Disabled'}</label></header><h2>{schedule.name}</h2><p>{cadenceLabel(schedule)} · {schedule.timezone}</p><dl><div><dt>Next run</dt><dd>{formatRun(schedule.nextRun)}</dd></div><div><dt>Previous run</dt><dd>{formatRun(schedule.previousRun)}</dd></div></dl><button className="text-button" onClick={() => setEditing(schedule)}>Edit schedule</button></article>)}</section> : <EmptyState title="No schedules yet" description="Create a recurring schedule for an existing automation." action={{ label: 'Create schedule', onClick: startNew }} />}
  </div>
}
