import type { ApprovalService } from './ApprovalService'
import type { ActivityService } from './ActivityService'
import type { CaptureDestination, CaptureDestinationAdapter, CaptureItem, CaptureKind, CaptureSuggestion } from '../models/capture'
import type { LocalStore } from '../storage/LocalStore'
import { localStore } from '../storage/LocalStore.ts'
import { storageKeys } from '../storage/storageKeys.ts'

export class CaptureInboxService {
  private readonly approvals: ApprovalService; private readonly destinations: Partial<Record<CaptureDestination, CaptureDestinationAdapter>>; private readonly activity?: ActivityService; private readonly store: LocalStore
  constructor(approvals: ApprovalService, destinations: Partial<Record<CaptureDestination, CaptureDestinationAdapter>>, activity?: ActivityService, store: LocalStore = localStore) { this.approvals = approvals; this.destinations = destinations; this.activity = activity; this.store = store }
  list() { return this.store.read<CaptureItem[]>(storageKeys.captures, []) }
  capture(text: string, kind: CaptureKind = 'unclassified', source: CaptureItem['source'] = 'inbox', now = new Date()) { const clean = text.trim(); if (!clean) throw new Error('Capture text is required.'); const items = this.list(); const item: CaptureItem = { id: `capture-${now.getTime()}-${items.length + 1}`, text: clean, kind, source, capturedAt: now.toISOString(), state: 'inbox' }; this.store.write(storageKeys.captures, [item, ...items]); return item }
  suggest(id: string): CaptureSuggestion | undefined { const item = this.list().find(value => value.id === id); if (!item) return; const text = item.text.toLowerCase(); const destination: CaptureDestination = item.kind === 'task' || item.kind === 'reminder' ? 'tasks' : item.kind === 'note' ? 'notes' : item.kind === 'project-candidate' ? 'projects' : item.kind === 'link' || /^https?:/.test(text) ? 'reading' : /video|article|post|content/.test(text) ? 'content' : 'notes'; return { destination, reason: `Suggested from capture kind “${item.kind}” and text signals.` } }
  requestMove(id: string, destination: CaptureDestination) { const item = this.list().find(value => value.id === id); const adapter = this.destinations[destination]; if (!item || item.state === 'moved' || !adapter) return; const request = this.approvals.request({ source: 'Capture Inbox', action: 'capture.move', summary: `Move capture to ${destination}`, risk: 'medium', correlationId: `capture:${item.id}`, payloadPreview: { captureId: item.id, destination, originalCapturedAt: item.capturedAt } }, () => { const current = this.list().find(value => value.id === id); if (!current || current.state === 'moved') return; const destinationId = adapter.move(current); const movedAt = new Date().toISOString(); this.update(id, value => ({ ...value, state: 'moved', destination, destinationId, movedAt })); this.activity?.publish({ id: `capture-moved-${id}`, timestamp: movedAt, source: 'System', type: 'Capture moved', description: `Inbox capture moved to ${destination}.`, status: 'success', route: destination, correlationId: `capture:${id}` }) }); this.update(id, value => ({ ...value, state: 'awaiting-approval', suggestedDestination: destination })); return request }
  private update(id: string, change: (item: CaptureItem) => CaptureItem) { this.store.write(storageKeys.captures, this.list().map(item => item.id === id ? change(item) : item)) }
}
