import type { BackupCollection } from '../services/LocalDataTransfer'

export type BackupRunStatus = 'ok' | 'failed'
export type BackupIntegrityStatus = 'verified' | 'failed' | 'unverified'
export type BackupJobHealth = 'healthy' | 'stale' | 'failed' | 'never-run'

/** How often a scheduled backup is expected to run, and how long after the last successful run it is considered stale. There is no real cron in this codebase yet; scheduling is simulated deterministically from elapsed time between checks. */
export interface BackupSchedule { intervalHours: number; staleAfterHours: number }

/** How many recent snapshots, and how many days of history, a backup job keeps. The single most recent snapshot is always retained regardless of age so a stalled job remains visible rather than disappearing. */
export interface BackupRetentionPolicy { maxSnapshots: number; maxAgeDays: number }

/**
 * One backup run's metadata. Never carries a raw payload: `counts` and `checksum` are enough
 * to inspect age, status, and integrity without exposing the underlying records here. A failed
 * run still produces a snapshot (so failures are visible and retained) but has no restorable
 * payload behind it.
 */
export interface BackupSnapshot {
  id: string
  createdAt: string
  status: BackupRunStatus
  failureReason?: string
  counts: Record<BackupCollection, number>
  preferenceCount: number
  checksum: string
  sizeBytes: number
  integrity: BackupIntegrityStatus
  integrityCheckedAt?: string
  integrityIssues: string[]
}

export interface BackupData {
  schedule: BackupSchedule
  retention: BackupRetentionPolicy
  snapshots: BackupSnapshot[]
  health: BackupJobHealth
  lastSuccessAt?: string
  nextDueAt?: string
}

/** Result of a non-destructive integrity check: recomputes and re-validates a stored backup's payload without touching production data. */
export interface BackupIntegrityResult { snapshotId: string; checkedAt: string; status: BackupIntegrityStatus; issues: string[] }

/** A read-only preview of what a restore would change, generated by comparing a backup's recorded counts against current live counts. Never written anywhere; a real restore always goes through approval separately. */
export interface RestorePreview {
  snapshotId: string
  generatedAt: string
  backupCounts: Record<BackupCollection, number>
  currentCounts: Record<BackupCollection, number>
  preferenceCount: number
  changedCollections: BackupCollection[]
  warnings: string[]
}
